// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7xqvCzz-XKsYxOzwp-IxBFkmCdZ-iYTQ',
    appId: '1:310192679872:web:b4c93890dd47463f23b625',
    messagingSenderId: '310192679872',
    projectId: 'silentshield-681a1',
    authDomain: 'silentshield-681a1.firebaseapp.com',
    storageBucket: 'silentshield-681a1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrOQ0iNsv3dfuSuAABJ9xy_XmNJhNEfCU',
    appId: '1:310192679872:android:1bdb7c94e5ce4daf23b625',
    messagingSenderId: '310192679872',
    projectId: 'silentshield-681a1',
    storageBucket: 'silentshield-681a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV1AXYfEz3ex_eqR_q6eKVIXX87OyI02U',
    appId: '1:310192679872:ios:0cf48a36cad0954823b625',
    messagingSenderId: '310192679872',
    projectId: 'silentshield-681a1',
    storageBucket: 'silentshield-681a1.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV1AXYfEz3ex_eqR_q6eKVIXX87OyI02U',
    appId: '1:310192679872:ios:0cf48a36cad0954823b625',
    messagingSenderId: '310192679872',
    projectId: 'silentshield-681a1',
    storageBucket: 'silentshield-681a1.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7xqvCzz-XKsYxOzwp-IxBFkmCdZ-iYTQ',
    appId: '1:310192679872:web:ce2435bff1a1332c23b625',
    messagingSenderId: '310192679872',
    projectId: 'silentshield-681a1',
    authDomain: 'silentshield-681a1.firebaseapp.com',
    storageBucket: 'silentshield-681a1.firebasestorage.app',
  );
}
